name: Python application - Updated

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      continue-on-error: true
      id: build

    - name: Save Build Log
      run: echo "${{ steps.build.outcome }}" > build_output.txt

    - name: Test with pytest
      run: |
        pytest app.py > test_output.txt
      continue-on-error: true
      id: test

    - name: Save Test Log
      run: echo "${{ steps.test.outcome }}" > test_output.txt

    - name: Upload SummaryResult artifact
      uses: actions/upload-artifact@v2
      with:
        name: SummaryResult
        path: |
          build_output.txt
          test_output.txt